const config=window.LMS_CONFIG,token=sessionStorage.getItem("lms_access_token")||"";
const headers={apikey:config.supabasePublishableKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json"};
const cache={subjects:[],questions:[],blueprints:[],exams:[],violations:[]};
const labels={dashboard:"Tổng quan hệ thống",questions:"Ngân hàng câu hỏi",blueprints:"Ma trận đề",exams:"Quản lý kỳ thi",violations:"Nhật ký vi phạm"};
async function api(path,options={}){const res=await fetch(`${config.supabaseUrl}/rest/v1/${path}`,{...options,headers:{...headers,...options.headers}});if(!res.ok)throw new Error((await res.text())||`HTTP ${res.status}`);return res.status===204?null:res.json()}
async function init(){if(!token)return deny("Bạn chưa đăng nhập.");try{const u=await fetch(`${config.supabaseUrl}/auth/v1/user`,{headers});if(!u.ok)throw new Error("Phiên đăng nhập đã hết hạn.");const user=await u.json(),profiles=await api(`profiles?id=eq.${user.id}&select=id,full_name,role`),profile=profiles[0];if(!profile||!["teacher","reviewer","admin"].includes(profile.role))return deny("Tài khoản không có quyền quản trị.");document.querySelector("#admin-user").textContent=`${profile.full_name||user.email} · ${profile.role}`;const [subjects,questions,blueprints,exams,violations]=await Promise.all([api("subjects?select=id,code,name&order=name"),api("question_items?select=id,code,stem,topic,cognitive_level,status,subjects(name)&order=created_at.desc&limit=100"),api("blueprints?select=id,name,year,status,subjects(name)&order=created_at.desc"),api("exams?select=id,title,duration_minutes,status,subjects(name)&order=created_at.desc"),api("violations?select=id,event_type,occurred_at,attempt_id&order=occurred_at.desc&limit=100")]);Object.assign(cache,{subjects,questions,blueprints,exams,violations});document.querySelector("#access-state").hidden=true;document.querySelector("#admin-app").hidden=false;render("dashboard");fillSubjects()}catch(err){deny(err.message)}}
function deny(message){document.querySelector("#access-state").innerHTML=`<h2>Không thể mở trang quản trị</h2><p>${message}</p><a class="button primary" href="index.html">Đăng nhập tại trang chính</a>`}
function render(view){document.querySelector("#view-title").textContent=labels[view];document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===view));document.querySelector("#new-item").hidden=view!=="dashboard"&&view!=="questions";document.querySelector("#stats").innerHTML=[["Câu hỏi",cache.questions.length],["Ma trận",cache.blueprints.length],["Kỳ thi",cache.exams.length],["Vi phạm",cache.violations.length]].map(([x,n])=>`<article class="stat-card"><small>${x}</small><strong>${n}</strong><span>Dữ liệu hiện có</span></article>`).join("");renderTable(view==="dashboard"?"questions":view)}
function renderTable(view){const head=document.querySelector("#data-head"),body=document.querySelector("#data-body"),caption=document.querySelector("#table-caption");if(view==="questions"){caption.textContent="Ngân hàng câu hỏi";head.innerHTML="<tr><th>Mã</th><th>Môn</th><th>Nội dung</th><th>Chủ đề</th><th>Mức độ</th><th>Trạng thái</th></tr>";body.innerHTML=cache.questions.map(x=>`<tr><td><b>${x.code}</b></td><td>${x.subjects?.name||"—"}</td><td>${x.stem.slice(0,65)}${x.stem.length>65?"…":""}</td><td>${x.topic||"—"}</td><td>${x.cognitive_level||"—"}</td><td><span class="status">${x.status}</span></td></tr>`).join("")||empty(6)}if(view==="blueprints"){caption.textContent="Ma trận đề";head.innerHTML="<tr><th>Tên</th><th>Môn</th><th>Năm</th><th>Trạng thái</th></tr>";body.innerHTML=cache.blueprints.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.subjects?.name||"—"}</td><td>${x.year}</td><td><span class="status">${x.status}</span></td></tr>`).join("")||empty(4)}if(view==="exams"){caption.textContent="Kỳ thi";head.innerHTML="<tr><th>Tên kỳ thi</th><th>Môn</th><th>Thời lượng</th><th>Trạng thái</th></tr>";body.innerHTML=cache.exams.map(x=>`<tr><td><b>${x.title}</b></td><td>${x.subjects?.name||"—"}</td><td>${x.duration_minutes} phút</td><td><span class="status">${x.status}</span></td></tr>`).join("")||empty(4)}if(view==="violations"){caption.textContent="Sự kiện giám sát";head.innerHTML="<tr><th>Thời gian</th><th>Loại vi phạm</th><th>Mã lượt thi</th></tr>";body.innerHTML=cache.violations.map(x=>`<tr><td>${new Date(x.occurred_at).toLocaleString("vi-VN")}</td><td>${x.event_type}</td><td>${x.attempt_id}</td></tr>`).join("")||empty(3)}}
function empty(cols){return`<tr><td colspan="${cols}">Chưa có dữ liệu.</td></tr>`}function fillSubjects(){document.querySelector("#q-subject").innerHTML=cache.subjects.map(x=>`<option value="${x.id}">${x.name}</option>`).join("")}
async function saveQuestion(event){event.preventDefault();const msg=document.querySelector("#question-message");msg.textContent="Đang lưu…";try{const payload={subject_id:document.querySelector("#q-subject").value,code:document.querySelector("#q-code").value.trim(),stem:document.querySelector("#q-stem").value.trim(),options:document.querySelector("#q-options").value.split("\n").map(x=>x.trim()).filter(Boolean),cognitive_level:document.querySelector("#q-level").value,topic:document.querySelector("#q-topic").value.trim()||null,status:"draft"},rows=await api("question_items",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)});cache.questions.unshift({...rows[0],subjects:{name:cache.subjects.find(x=>x.id===payload.subject_id)?.name}});document.querySelector("#question-modal").close();event.target.reset();render("questions")}catch(err){msg.textContent=err.message}}
document.querySelectorAll("[data-view]").forEach(x=>x.onclick=()=>render(x.dataset.view));document.querySelector("#new-item").onclick=()=>document.querySelector("#question-modal").showModal();document.querySelectorAll("[data-close-modal]").forEach(x=>x.onclick=()=>x.closest("dialog").close());document.querySelector("#question-form").onsubmit=saveQuestion;init();
