const config=window.LMS_CONFIG;
const fallbackExams=[{id:"demo-toan",subject:"TOÁN",title:"Đề thi thử Toán · Mã 0101",duration_minutes:90,question_count:22,status:"Sẵn sàng"},{id:"demo-van",subject:"NGỮ VĂN",title:"Đề thi thử Ngữ văn · Mã 0201",duration_minutes:120,question_count:2,status:"Sắp mở"},{id:"demo-anh",subject:"TIẾNG ANH",title:"Đề thi thử Tiếng Anh · Mã 0301",duration_minutes:50,question_count:40,status:"Sẵn sàng"}];
const state={accessToken:sessionStorage.getItem("lms_access_token")||"",refreshToken:sessionStorage.getItem("lms_refresh_token")||"",user:null,profile:null};
const apiHeaders=()=>({apikey:config.supabasePublishableKey,Authorization:`Bearer ${state.accessToken||config.supabasePublishableKey}`});
function storeSession(data){state.accessToken=data.access_token||"";state.refreshToken=data.refresh_token||"";state.user=data.user||null;sessionStorage.setItem("lms_access_token",state.accessToken);sessionStorage.setItem("lms_refresh_token",state.refreshToken)}
function clearSession(){state.accessToken="";state.refreshToken="";state.user=null;state.profile=null;sessionStorage.removeItem("lms_access_token");sessionStorage.removeItem("lms_refresh_token")}
async function refreshSession(){if(!state.refreshToken)return false;const res=await fetch(`${config.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:config.supabasePublishableKey,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:state.refreshToken})});if(!res.ok){clearSession();return false}storeSession(await res.json());return true}
async function loadProfile(){if(!state.accessToken){updateAccountUI();return}let res=await fetch(`${config.supabaseUrl}/auth/v1/user`,{headers:apiHeaders()});if(res.status===401&&await refreshSession())res=await fetch(`${config.supabaseUrl}/auth/v1/user`,{headers:apiHeaders()});if(!res.ok){clearSession();updateAccountUI();return}state.user=await res.json();const p=await fetch(`${config.supabaseUrl}/rest/v1/profiles?id=eq.${state.user.id}&select=id,full_name,role,school_name`,{headers:apiHeaders()});if(p.ok)state.profile=(await p.json())[0]||null;updateAccountUI()}
function isStaff(){return["teacher","reviewer","admin"].includes(state.profile?.role)}
function updateAccountUI(){const signed=Boolean(state.user),name=state.profile?.full_name||state.user?.email||"Tài khoản";document.querySelector("#auth-label").textContent=signed?name:"Đăng nhập";document.querySelector("#login-fields").hidden=signed;document.querySelector("#account-panel").hidden=!signed;document.querySelector("#account-name").textContent=name;document.querySelector("#admin-link").hidden=!isStaff();document.querySelector("#admin-button").hidden=!isStaff()}
async function loadExams(){let exams=fallbackExams;if(state.accessToken)try{const res=await fetch(`${config.supabaseUrl}/rest/v1/exams?select=id,title,duration_minutes,status,subjects(name),exam_questions(count)&status=eq.published&order=created_at.desc`,{headers:apiHeaders()});if(res.ok){const rows=await res.json();if(rows.length)exams=rows.map(x=>({...x,subject:x.subjects?.name||"KỲ THI",question_count:x.exam_questions?.[0]?.count??"—",status:"Sẵn sàng"}))}}catch(error){console.info("Đang dùng dữ liệu minh họa.")}document.querySelector("#exam-grid").innerHTML=exams.map(exam=>`<article class="exam-card"><span class="tag">${exam.status}</span><h3>${exam.title}</h3><p class="muted">Mô phỏng cấu trúc thi, lưu bài định kỳ và ghi nhận sự kiện giám sát.</p><div class="exam-meta"><span>◷ ${exam.duration_minutes} phút</span><span>▤ ${exam.question_count} câu</span><span>${exam.subject}</span></div><a class="button primary" href="exam.html?id=${encodeURIComponent(exam.id)}">Vào phòng thi</a></article>`).join("")}
async function login(){const email=document.querySelector("#email").value.trim(),password=document.querySelector("#password").value,msg=document.querySelector("#auth-message");msg.textContent="Đang xác thực…";try{const res=await fetch(`${config.supabaseUrl}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:config.supabasePublishableKey,"Content-Type":"application/json"},body:JSON.stringify({email,password})}),data=await res.json();if(!res.ok)throw new Error(data.msg||data.error_description||"Không thể đăng nhập");storeSession(data);await loadProfile();await loadExams();msg.textContent=""}catch(err){msg.textContent=err.message}}
async function logout(){if(state.accessToken)await fetch(`${config.supabaseUrl}/auth/v1/logout`,{method:"POST",headers:apiHeaders()}).catch(()=>{});clearSession();updateAccountUI();await loadExams();document.querySelector("#auth-modal").close()}
document.querySelector("#mobile-menu").addEventListener("click",()=>document.querySelector("#top-nav").classList.toggle("open"));document.querySelector("#auth-button").addEventListener("click",()=>document.querySelector("#auth-modal").showModal());document.querySelector("#login-button").addEventListener("click",login);document.querySelector("#logout-button").addEventListener("click",logout);document.querySelectorAll("[data-open-modal]").forEach(el=>el.addEventListener("click",()=>document.querySelector(`#${el.dataset.openModal}`).showModal()));document.querySelectorAll("[data-close-modal]").forEach(el=>el.addEventListener("click",()=>el.closest("dialog").close()));document.querySelectorAll("dialog").forEach(dialog=>dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()}));
(async()=>{await loadProfile();await loadExams()})();
