const config=window.LMS_CONFIG;
const examId=new URLSearchParams(location.search).get("id")||"";
let questions=[],exam=null,user=null,attemptId="",current=0,remaining=0,violations=0,started=false,finished=false,lastViolation=0,timerId=null,presenceTimer=null,assignmentDeadline=0,webcamStatus="off";
const answers={};
let token=sessionStorage.getItem("lms_access_token")||"";
let refreshToken=sessionStorage.getItem("lms_refresh_token")||"";

const headers=(extra={})=>({apikey:config.supabasePublishableKey,Authorization:`Bearer ${token}`,...extra});
async function api(path,options={}){
 let response=await fetch(`${config.supabaseUrl}${path}`,{...options,headers:{...headers(),...(options.headers||{})}});
 if(response.status===401&&refreshToken){
  const renewed=await fetch(`${config.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:config.supabasePublishableKey,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:refreshToken})});
  if(renewed.ok){const session=await renewed.json();token=session.access_token;refreshToken=session.refresh_token||refreshToken;sessionStorage.setItem("lms_access_token",token);sessionStorage.setItem("lms_refresh_token",refreshToken);response=await fetch(`${config.supabaseUrl}${path}`,{...options,headers:{...headers(),...(options.headers||{})}})}
 }
 return response;
}
function formatTime(value){const safe=Math.max(0,value),h=String(Math.floor(safe/3600)).padStart(2,"0"),m=String(Math.floor(safe%3600/60)).padStart(2,"0"),s=String(safe%60).padStart(2,"0");return`${h}:${m}:${s}`}
function setGateError(message){document.querySelector("#gate-title").textContent="Không thể mở kỳ thi";document.querySelector("#gate-status").textContent=message;document.querySelector("#consent").disabled=true;document.querySelector("#start-exam").disabled=true;document.querySelector("#connection").textContent="● Lỗi tải đề"}
async function loadExam(){
 if(!examId||!token){setGateError("Vui lòng đăng nhập và chọn kỳ thi được phân công từ trang chính.");return}
 try{
  const userRes=await api("/auth/v1/user");if(!userRes.ok)throw new Error("Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.");user=await userRes.json();
  const assignmentRes=await api(`/rest/v1/exam_assignments?exam_id=eq.${encodeURIComponent(examId)}&student_id=eq.${encodeURIComponent(user.id)}&status=eq.active&select=available_from,available_until,duration_override_minutes&limit=1`);if(!assignmentRes.ok)throw new Error("Không đọc được lịch phân công kỳ thi.");const assignments=await assignmentRes.json();if(!assignments.length)throw new Error("Kỳ thi chưa được phân công cho tài khoản này.");const assignment=assignments[0],now=Date.now();assignmentDeadline=assignment.available_until?new Date(assignment.available_until).getTime():0;if(assignment.available_from&&now<new Date(assignment.available_from).getTime())throw new Error(`Kỳ thi mở lúc ${new Date(assignment.available_from).toLocaleString("vi-VN")}.`);if(assignmentDeadline&&now>assignmentDeadline)throw new Error(`Kỳ thi đã đóng lúc ${new Date(assignment.available_until).toLocaleString("vi-VN")}.`);
  const select=encodeURIComponent("id,title,duration_minutes,status,exam_questions(position,points,exam_sections(code,title,instructions,stimulus,start_position,end_position),question_items(id,stem,options,item_type))");
  const examRes=await api(`/rest/v1/exams?id=eq.${encodeURIComponent(examId)}&status=eq.published&select=${select}`);
  if(!examRes.ok)throw new Error("Không đọc được dữ liệu kỳ thi.");
  const rows=await examRes.json();if(!rows.length)throw new Error("Kỳ thi không tồn tại, chưa được xuất bản hoặc chưa phân công cho tài khoản này.");
  exam=rows[0];if(assignment.duration_override_minutes)exam.duration_minutes=assignment.duration_override_minutes;questions=(exam.exam_questions||[]).sort((a,b)=>a.position-b.position).map(row=>({id:row.question_items.id,position:row.position,stem:row.question_items.stem,options:Array.isArray(row.question_items.options)?row.question_items.options:[],itemType:row.question_items.item_type,section:row.exam_sections||null}));
  if(!questions.length)throw new Error("Kỳ thi chưa có câu hỏi.");
  remaining=Math.min(exam.duration_minutes*60,assignmentDeadline?Math.max(0,Math.floor((assignmentDeadline-Date.now())/1000)):Infinity);document.querySelector("#exam-name").textContent=exam.title;document.querySelector("#timer").textContent=formatTime(remaining);document.title=`${exam.title} | LMS ExamHub`;
  document.querySelector("#gate-title").textContent=exam.title;document.querySelector("#gate-status").textContent=`${questions.length} câu · ${exam.duration_minutes} phút. Hãy kiểm tra thiết bị trước khi bắt đầu.`;document.querySelector("#consent").disabled=false;document.querySelector("#connection").textContent="● Đề đã sẵn sàng";render();await restoreSubmittedAttempt();
 }catch(error){setGateError(error.message)}
}
function render(){
 if(!questions.length)return;const q=questions[current],section=q.section||{title:"Trắc nghiệm",instructions:"Chọn phương án đúng.",stimulus:""};document.querySelector("#question-index").textContent=`Câu ${q.position}/${questions.length}`;document.querySelector("#question-type").textContent=section.title.toUpperCase();document.querySelector("#section-title").textContent=section.title;document.querySelector("#section-instructions").textContent=section.instructions||"";document.querySelector("#section-stimulus").textContent=section.stimulus||"";document.querySelector("#section-context").classList.toggle("no-stimulus",!section.stimulus);
 const groupedStem=section.stimulus?q.stem.match(/Question\s+\d+:\s*([\s\S]*)$/i):null;document.querySelector("#question-stem").textContent=groupedStem?(groupedStem[1].trim()||`Question ${q.position}`):q.stem;
 const options=document.querySelector("#options");options.replaceChildren();q.options.forEach((value,index)=>{const button=document.createElement("button");button.className=`option ${answers[q.id]===index?"selected":""}`;button.dataset.option=index;const label=document.createElement("b");label.textContent=String.fromCharCode(65+index);const text=document.createElement("span");text.textContent=String(value);button.append(label,text);button.onclick=()=>selectAnswer(q.id,index);options.append(button)});
 const map=document.querySelector("#question-map");map.replaceChildren();questions.forEach((item,index)=>{const button=document.createElement("button");button.textContent=index+1;button.className=`${index===current?"active":""} ${answers[item.id]!==undefined?"answered":""}`;button.onclick=()=>{current=index;render()};map.append(button)});
 document.querySelector("#prev").disabled=current===0;document.querySelector("#next").disabled=current===questions.length-1;
}
async function ensureAttempt(){
 const query=`/rest/v1/attempts?exam_id=eq.${encodeURIComponent(examId)}&student_id=eq.${encodeURIComponent(user.id)}&select=id,status,started_at&limit=1`;
 let response=await api(query);if(!response.ok)throw new Error("Không thể kiểm tra lượt thi.");let rows=await response.json();
 if(rows.length){if(rows[0].status==="submitted")throw new Error("Tài khoản này đã nộp bài cho kỳ thi.");attemptId=rows[0].id;const elapsed=Math.floor((Date.now()-new Date(rows[0].started_at).getTime())/1000),deadlineLeft=assignmentDeadline?Math.max(0,Math.floor((assignmentDeadline-Date.now())/1000)):Infinity;remaining=Math.min(Math.max(0,exam.duration_minutes*60-elapsed),deadlineLeft);document.querySelector("#timer").textContent=formatTime(remaining);const saved=await api(`/rest/v1/responses?attempt_id=eq.${attemptId}&select=question_id,answer`);if(saved.ok)(await saved.json()).forEach(item=>{if(Number.isInteger(item.answer?.selected_option))answers[item.question_id]=item.answer.selected_option});render();return}
 response=await api("/rest/v1/attempts",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({exam_id:examId,student_id:user.id,status:"in_progress"})});
 if(!response.ok)throw new Error("Không thể tạo lượt thi. Hãy kiểm tra lại phân công kỳ thi.");attemptId=(await response.json())[0].id;
}
async function gradeAttempt(){const response=await api("/rest/v1/rpc/submit_attempt",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({p_attempt_id:attemptId})});if(!response.ok)throw new Error((await response.text())||"Không thể chấm bài.");return response.json()}
function showResult(result){finished=true;started=false;clearInterval(timerId);clearInterval(presenceTimer);sendPresence("offline");document.querySelector("#exam-gate").classList.add("hidden");document.querySelector("#result-score").textContent=Number(result.score||0).toFixed(2).replace(".",",");document.querySelector("#result-total").textContent=`/ ${Number(result.total_points||10).toFixed(2).replace(".",",")} điểm`;document.querySelector("#result-correct").textContent=result.correct_count||0;document.querySelector("#result-incorrect").textContent=result.incorrect_count||0;document.querySelector("#result-unanswered").textContent=result.unanswered_count||0;document.querySelector("#result-violations").textContent=result.violation_count||0;const map=document.querySelector("#result-map");map.replaceChildren();(result.details||[]).forEach(item=>{const cell=document.createElement("span");cell.textContent=item.position;cell.className=item.is_correct===true?"correct":item.is_correct===false?"incorrect":"";cell.title=item.is_correct===true?"Đúng":item.is_correct===false?"Sai":"Chưa trả lời";map.append(cell)});if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});if(!document.querySelector("#finish-dialog").open)document.querySelector("#finish-dialog").showModal()}
async function restoreSubmittedAttempt(){const response=await api(`/rest/v1/attempts?exam_id=eq.${encodeURIComponent(examId)}&student_id=eq.${encodeURIComponent(user.id)}&status=eq.submitted&select=id&limit=1`);if(!response.ok)return;const rows=await response.json();if(!rows.length)return;attemptId=rows[0].id;try{showResult(await gradeAttempt())}catch(error){setGateError(error.message)}}
async function start(){
 document.querySelector("#start-exam").disabled=true;document.querySelector("#gate-status").textContent="Đang tạo lượt thi…";
 try{await ensureAttempt()}catch(error){setGateError(error.message);return}
 started=true;document.querySelector("#exam-gate").classList.add("hidden");
 try{await document.documentElement.requestFullscreen()}catch(e){violate("Không thể vào chế độ toàn màn hình")}
 try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false});document.querySelector("#camera").srcObject=stream;webcamStatus="active"}catch(e){webcamStatus=e?.name==="NotAllowedError"?"denied":"error";violate("Webcam bị từ chối hoặc không khả dụng")}
 await sendPresence("online");presenceTimer=setInterval(()=>sendPresence(document.hidden?"unstable":"online"),8000);timerId=setInterval(tick,1000);render();queueSave("start",{exam_id:examId});
}
function tick(){if(finished)return;remaining--;document.querySelector("#timer").textContent=formatTime(remaining);if(remaining<=0)finish()}
async function selectAnswer(questionId,index){answers[questionId]=index;render();if(!attemptId)return;const response=await api("/rest/v1/responses?on_conflict=attempt_id,question_id",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({attempt_id:attemptId,question_id:questionId,answer:{selected_option:index}})});document.querySelector("#connection").textContent=response.ok?"● Đã lưu":"● Chờ đồng bộ";queueSave("response",{question_id:questionId,selected_option:index})}
function violate(message){if(!started||finished)return;const now=Date.now();if(now-lastViolation<1200)return;lastViolation=now;violations++;document.querySelector("#violation-count").textContent=violations;document.querySelector("#warning-message").textContent=message;document.querySelector("#warning-dialog").showModal();queueSave("violation",{type:message,occurred_at:new Date().toISOString(),page_visibility:document.visibilityState})}
async function queueSave(kind,payload){
 const event={attempt_id:attemptId,kind,payload,user_agent:navigator.userAgent,created_at:new Date().toISOString()},queue=JSON.parse(localStorage.getItem("lms_event_queue")||"[]");queue.push(event);localStorage.setItem("lms_event_queue",JSON.stringify(queue.slice(-200)));
 if(config.appsScriptUrl)fetch(config.appsScriptUrl,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain"},body:JSON.stringify(event)}).catch(()=>{});
 if(token&&attemptId&&kind==="violation")await api("/rest/v1/violations",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({attempt_id:attemptId,event_type:payload.type,details:payload})}).catch(()=>{});
}
async function finish(){if(finished||!attemptId)return;finished=true;clearInterval(timerId);document.querySelector("#submit").disabled=true;document.querySelector("#connection").textContent="● Đang nộp và chấm bài…";await queueSave("finish",{answers,remaining,violations});try{const result=await gradeAttempt();document.querySelector("#connection").textContent="● Đã nộp bài";showResult(result)}catch(error){finished=false;document.querySelector("#submit").disabled=false;document.querySelector("#connection").textContent="● Chưa thể nộp bài";alert(error.message)}}
async function sendPresence(connectionStatus="online"){if(!token||!attemptId||!user)return;if(finished){clearInterval(presenceTimer);connectionStatus="offline"}const payload={attempt_id:attemptId,exam_id:examId,student_id:user.id,webcam_status:webcamStatus,connection_status:connectionStatus,current_question:current+1,answered_count:Object.keys(answers).length,last_seen:new Date().toISOString(),device_info:{platform:navigator.platform||"",visibility:document.visibilityState}};await api("/rest/v1/exam_presence?on_conflict=attempt_id",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(payload),keepalive:true}).catch(()=>{})}
document.querySelector("#consent").onchange=e=>document.querySelector("#start-exam").disabled=!e.target.checked||!exam;
document.querySelector("#start-exam").onclick=start;document.querySelector("#prev").onclick=()=>{current=Math.max(0,current-1);render()};document.querySelector("#next").onclick=()=>{current=Math.min(questions.length-1,current+1);render()};document.querySelector("#submit").onclick=finish;
document.querySelector("#return-exam").onclick=async()=>{document.querySelector("#warning-dialog").close();if(!document.fullscreenElement)try{await document.documentElement.requestFullscreen()}catch(e){}};
document.addEventListener("visibilitychange",()=>{if(document.hidden)violate("Rời khỏi màn hình làm bài hoặc chuyển ứng dụng")});document.addEventListener("fullscreenchange",()=>{if(started&&!finished&&!document.fullscreenElement)violate("Thoát chế độ toàn màn hình")});document.addEventListener("contextmenu",e=>{e.preventDefault();violate("Sử dụng chuột phải")});document.addEventListener("copy",e=>{e.preventDefault();violate("Sao chép nội dung đề thi")});document.addEventListener("cut",e=>{e.preventDefault();violate("Cắt nội dung đề thi")});document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&["c","x","u","s","p"].includes(e.key.toLowerCase())){e.preventDefault();violate(`Sử dụng tổ hợp phím bị hạn chế (${e.key.toUpperCase()})`)}if(e.key==="PrintScreen")violate("Sử dụng phím chụp màn hình")});window.addEventListener("beforeunload",e=>{if(started&&!finished){e.preventDefault();e.returnValue=""}});
document.addEventListener("selectstart",e=>{e.preventDefault();violate("Cố gắng chọn văn bản hoặc tra cứu từ điển")});document.addEventListener("dragstart",e=>{e.preventDefault();violate("Cố gắng kéo nội dung đề thi")});document.addEventListener("dblclick",e=>{e.preventDefault();getSelection()?.removeAllRanges();violate("Cố gắng chọn từ để tra cứu")});document.addEventListener("selectionchange",()=>{const selection=getSelection();if(selection&&!selection.isCollapsed){selection.removeAllRanges();violate("Cố gắng chọn văn bản hoặc tra cứu từ điển")}});
document.addEventListener("visibilitychange",()=>sendPresence(document.hidden?"unstable":"online"));window.addEventListener("pagehide",()=>{if(started&&!finished)sendPresence("offline")});
loadExam();

